name: Run Hash Script

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  run-hash-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone secondary repository
      run: |
        git clone https://github.com/uaineteine/hash_ds.git

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies of hash_ds
      run: |
        python -m pip install --upgrade pip
        pip install -r hash_ds/requirements.txt
    
    - name: Install dependencies of this applicaton
      run: |
        pip install -r requirements.txt

    - name: Copy config ini for test
      run: cp -rf .github/workflows/test_config.ini config.ini

    - name: Run hash script
      run: |
        python hash_ds_chunkify.py hash_ds/testdata/data1.psv usernames,Header2 hashed_data1.parquet

